language: java
script:
  - cd ./simple-api/
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=roxannekey
  - cd ..

  # Connexion à Docker
  - docker login -u $DOCKER_USER -p $DOCKER_PWD

  # Build
  - docker build -t $DOCKER_USER/Docker-tp-2:database database
  - docker build -t $DOCKER_USER/Docker-tp-2:httpd httpd
  - docker build -t $DOCKER_USER/Docker-tp-2:simple-api simple-api

  # Publication des images
  - docker push $DOCKER_USER/Docker-tp-2:database
  - docker push $DOCKER_USER/Docker-tp-2:httpd
  - docker push $DOCKER_USER/Docker-tp-2:simple-api

cache:
    directories:
        - $HOME/.m2
services:
- docker
 addons:
    sonarcloud:
        organization: "roxannekey"
	token: $SONARCLOUD_TOKEN
