language: java
script:
  - cd ./simple-api/
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=roxannekey
  - cd ..
# Connexion à Docker
  - docker login -u $login -p $mdp

  # Build
  - docker build -t $login/docker-tp-2-main_database database
  - docker build -t $login/docker-tp-2-main_httpd httpd
  - docker build -t $login/docker-tp-2-main_simple-api simple-api

  # Publication des images
  - docker push $login/docker-tp-2-main_database database
  - docker push $login/docker-tp-2-main_httpd httpd
  - docker push $login/docker-tp-2-main_simple-api simple-api

cache:
    directories:
        - $HOME/.m2
services:
  - docker
addons:
 sonarcloud:
  organization: "roxannekey"
  token: $SONARCLOUD_TOKEN
