---
- name: App container
  docker_container:
    name: backend
    image: raudut/docker-tp-2-main_simple-api
    state: started
    networks:
      - name: app-network
    pull: yes
    env:
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
      SPRING_DATASOURCE_USER: "{{ db_user }}"
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
