---
- name: Proxy container
  docker_container:
    name: reverse_proxy
    image: raudut/docker-tp-2-main_httpd
    state: started
    pull: yes
    networks:
      - name: app-network
    ports:
      - "80:80"
